version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    ports:
      - "5000:5000"  # Map a port for your app if needed
    depends_on:
      - redis  # Ensure Redis starts before the app
    volumes:
      - .:/app  # Optional: Bind mount your local files for development
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379  # Default Redis port
    command: ["python", "chat.py"]  # Command to run your app

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"  # Map Redis default port for external access
    command: ["redis-server"]